version: "3.7"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:${KAFKA_VERSION:-latest}
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper:2888:3888
      KAFKA_OPTS: "-Dzookeeper.4lw.commands.whitelist=ruok"
    volumes:
      # OLD
      # - "./volumes/zookeeper/data:/var/lib/zookeeper/data"
      # - "./volumes/zookeeper/transactions:/var/lib/zookeeper/log"
      - "v-zookeeper-data:/var/lib/zookeeper/data"
      - "v-zookeeper-transactions:/var/lib/zookeeper/log"
    # OLD
    networks:
      - ${GLOBAL_NETWORK:-kafka}
    # networks:
    #   ${GLOBAL_NETWORK:-kafka}:
    #     external: true

volumes:
  v-zookeeper-data:
  v-zookeeper-transactions:
# networks:
#   ${GLOBAL_NETWORK:-kafka}:
#     external: true
